Repository rancher-sandbox/hypper, pull requests merged in 2021-03, with the labels that each got.

#53 Add status command
  cmd/hypper/root.go
  cmd/hypper/status.go
  cmd/hypper/status_test.go
  cmd/hypper/testdata/output/status-with-desc.txt
  cmd/hypper/testdata/output/status-with-notes.txt
  cmd/hypper/testdata/output/status-with-test-suite.txt
  cmd/hypper/testdata/output/status.json
  cmd/hypper/testdata/output/status.txt
  pkg/action/status.go
Labels: ready for review

#58 Add repo commands
  cmd/hypper/install.go
  cmd/hypper/repo.go
  cmd/hypper/repo_add.go
  cmd/hypper/repo_add_test.go
  cmd/hypper/repo_index.go
  cmd/hypper/repo_index_test.go
  cmd/hypper/repo_list.go
  cmd/hypper/repo_remove.go
  cmd/hypper/repo_remove_test.go
  cmd/hypper/repo_update.go
  cmd/hypper/repo_update_test.go
  cmd/hypper/root.go
  cmd/hypper/testdata/output/repo-add.txt
  cmd/hypper/testdata/output/repo-add2.txt
  cmd/hypper/testdata/repositories.yaml
  cmd/hypper/testdata/testcharts/vanilla-helm-compressedchart-0.1.0.tar.gz
  cmd/hypper/testdata/testcharts/vanilla-helm-compressedchart-0.1.0.tgz
  cmd/hypper/testdata/testcharts/vanilla-helm-compressedchart-0.2.0.tgz
  cmd/hypper/testdata/testcharts/vanilla-helm-compressedchart-0.3.0.tgz
  cmd/hypper/testdata/testcharts/vanilla-helm-reqtest-0.1.0.tgz
  cmd/hypper/testdata/testserver/index.yaml
  cmd/hypper/testdata/testserver/repository/repositories.yaml
  go.mod
  go.sum
  internal/test/ensure/ensure.go
  internal/third-party/helm/urlutil/urlutil.go
  internal/third-party/helm/urlutil/urlutil_test.go
  pkg/cli/environment.go
  pkg/cli/environment_test.go
  pkg/hypperpath/home.go
  pkg/hypperpath/home_unix_test.go
  pkg/hypperpath/home_windows_test.go
  pkg/hypperpath/lazypath.go
  pkg/hypperpath/lazypath_darwin.go
  pkg/hypperpath/lazypath_darwin_test.go
  pkg/hypperpath/lazypath_unix.go
  pkg/hypperpath/lazypath_unix_test.go
  pkg/hypperpath/lazypath_windows.go
  pkg/hypperpath/lazypath_windows_test.go
  pkg/hypperpath/xdg/xdg.go
  pkg/repo/chartrepo.go
  pkg/repo/index.go
  pkg/repo/index_test.go
  pkg/repo/repo.go
  pkg/repo/repo_test.go
  pkg/repo/testdata/chartmuseum-index.yaml
  pkg/repo/testdata/local-index-annotations.yaml
  pkg/repo/testdata/local-index-unordered.yaml
  pkg/repo/testdata/local-index.yaml
  pkg/repo/testdata/repositories.yaml
Labels: mvp, ready for review

#69 Create temp dir with hypper pattern
  internal/test/ensure/ensure.go
Labels: ready for review

#66 copyright/license check
  .github/workflows/license-check.yml
  Makefile
  cmd/hypper/hypper.go
  cmd/hypper/hypper_test.go
  cmd/hypper/install.go
  cmd/hypper/install_test.go
  cmd/hypper/list.go
  cmd/hypper/repo.go
  cmd/hypper/repo_add.go
  cmd/hypper/repo_list.go
  cmd/hypper/repo_remove.go
  cmd/hypper/repo_remove_test.go
  cmd/hypper/repo_update.go
  cmd/hypper/require/args.go
  cmd/hypper/root.go
  cmd/hypper/root_test.go
  cmd/hypper/status.go
  cmd/hypper/uninstall.go
  cmd/hypper/uninstall_test.go
  internal/test/ensure/ensure.go
  pkg/action/action.go
  pkg/action/action_test.go
  pkg/action/install.go
  pkg/action/install_test.go
  pkg/action/list.go
  pkg/action/status.go
  pkg/action/uninstall.go
  pkg/cli/environment.go
  pkg/cli/environment_test.go
  pkg/eyecandy/colors.go
  pkg/eyecandy/emoji.go
  pkg/eyecandy/emoji_test.go
  pkg/hypperpath/home.go
  pkg/hypperpath/home_unix_test.go
  pkg/hypperpath/home_windows_test.go
  pkg/hypperpath/lazypath.go
  pkg/hypperpath/lazypath_darwin.go
  pkg/hypperpath/lazypath_darwin_test.go
  pkg/hypperpath/lazypath_unix.go
  pkg/hypperpath/lazypath_unix_test.go
  pkg/hypperpath/lazypath_windows.go
  pkg/hypperpath/lazypath_windows_test.go
  pkg/hypperpath/xdg/xdg.go
  pkg/repo/chartrepo.go
  pkg/repo/index.go
  pkg/repo/repo.go
  pkg/repo/repo_test.go
  scripts/license_check.sh
Labels: ready for review

#64 Add new upgrade command
  cmd/hypper/dependency_build.go
  cmd/hypper/flags.go
  cmd/hypper/root.go
  cmd/hypper/testdata/output/upgrade-with-bad-dependencies.txt
  cmd/hypper/testdata/output/upgrade-with-bad-or-missing-existing-release.txt
  cmd/hypper/testdata/output/upgrade-with-install-timeout.txt
  cmd/hypper/testdata/output/upgrade-with-install.txt
  cmd/hypper/testdata/output/upgrade-with-missing-dependencies.txt
  cmd/hypper/testdata/output/upgrade-with-pending-install.txt
  cmd/hypper/testdata/output/upgrade-with-reset-values.txt
  cmd/hypper/testdata/output/upgrade-with-reset-values2.txt
  cmd/hypper/testdata/output/upgrade-with-timeout.txt
  cmd/hypper/testdata/output/upgrade-with-wait-for-jobs.txt
  cmd/hypper/testdata/output/upgrade-with-wait.txt
  cmd/hypper/testdata/output/upgrade.txt
  cmd/hypper/testdata/output/version-comp.txt
  cmd/hypper/testdata/output/version-invalid-comp.txt
  cmd/hypper/testdata/testcharts/chart-bad-requirements/.helmignore
  cmd/hypper/testdata/testcharts/chart-bad-requirements/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-bad-requirements/charts/reqsubchart/.helmignore
  cmd/hypper/testdata/testcharts/chart-bad-requirements/charts/reqsubchart/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-bad-requirements/charts/reqsubchart/values.yaml
  cmd/hypper/testdata/testcharts/chart-bad-requirements/values.yaml
  cmd/hypper/testdata/testcharts/chart-missing-deps/.helmignore
  cmd/hypper/testdata/testcharts/chart-missing-deps/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-missing-deps/charts/reqsubchart/.helmignore
  cmd/hypper/testdata/testcharts/chart-missing-deps/charts/reqsubchart/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-missing-deps/charts/reqsubchart/values.yaml
  cmd/hypper/testdata/testcharts/chart-missing-deps/values.yaml
  cmd/hypper/testdata/testcharts/chart-with-subchart-notes/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-subchart-notes/charts/subchart-with-notes/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-subchart-notes/charts/subchart-with-notes/templates/NOTES.txt
  cmd/hypper/testdata/testcharts/chart-with-subchart-notes/templates/NOTES.txt
  cmd/hypper/testdata/testcharts/chart-with-subchart-update/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-subchart-update/charts/subchart-with-notes/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-subchart-update/charts/subchart-with-notes/templates/NOTES.txt
  cmd/hypper/testdata/testcharts/chart-with-subchart-update/templates/NOTES.txt
  cmd/hypper/testdata/testcharts/upgradetest/templates/configmap.yaml
  cmd/hypper/testdata/testcharts/upgradetest/values.yaml
  cmd/hypper/upgrade.go
  cmd/hypper/upgrade_test.go
  internal/test/test.go
  pkg/action/history.go
  pkg/action/upgrade.go
Labels: ready for review

#72 Add missing action/upgrade.go license
  pkg/action/upgrade.go
Labels: CI, ready for review

#71 Add missing flag to Install
  cmd/hypper/install.go
Labels: bug, ready for review

#82 Set the client namespace on uninstall
  cmd/hypper/uninstall.go
  pkg/action/uninstall.go
Labels: WIP

#81 Deterministic names
  cmd/hypper/install.go
  cmd/hypper/install_test.go
  cmd/hypper/testdata/output/install-no-name-or-annot.txt
  pkg/action/install.go
  pkg/action/install_test.go
Labels: ready for review

#74 Fix namespace set on upgrade command
  cmd/hypper/hypper_test.go
  cmd/hypper/testdata/output/upgrade-with-install-release-name.txt
  cmd/hypper/testdata/output/upgrade-with-release-name.txt
  cmd/hypper/upgrade.go
  cmd/hypper/upgrade_test.go
  pkg/action/upgrade.go
  pkg/action/upgrade_test.go
Labels: bug, ready for review

#98 Add version command
  Makefile
  cmd/hypper/root.go
  cmd/hypper/testdata/output/version-client-shorthand.txt
  cmd/hypper/testdata/output/version-client.txt
  cmd/hypper/testdata/output/version-short.txt
  cmd/hypper/testdata/output/version-template.txt
  cmd/hypper/testdata/output/version.txt
  cmd/hypper/version.go
  cmd/hypper/version_test.go
  internal/version/version.go
Labels: ready for review

#99 Use relative path for bin dir in Makefile
  Makefile
Labels: bug, ready for review

#96 use goreleaser to provide hypper builds
  .github/workflows/releaser.yml
  .goreleaser.yml
Labels: ready for review

#101 Drop "Merge pull request" from changelog
  .goreleaser.yml
Labels: ready for review

#100 Remove print statement from version
  cmd/hypper/version.go
  internal/version/version.go
Labels: ready for review

#103 Enhance version set
  Makefile
Labels: ready for review

#89 Introduce common methods for setNamespace and Name
  cmd/hypper/install.go
  cmd/hypper/upgrade.go
  pkg/action/dependency_shared_test.go
  pkg/action/install.go
  pkg/action/install_test.go
  pkg/action/upgrade.go
  pkg/action/upgrade_test.go
  pkg/action/utils.go
Labels: enhancement, ready for review

#97 Add sh installer
  .github/workflows/get-hypper.yml
  .github/workflows/shellcheck.yml
  Makefile
  scripts/get-hypper
  scripts/license_check.sh
Labels: ready for review

#108 Only run shellcheck if scripts have changed
  .github/workflows/shellcheck.yml
Labels: ready for review

#106 Expand on the install tutorial
  docs/user/tutorials/installing.md
Labels: ready for review
