Repository rancher-sandbox/hypper, pull requests merged in 2021-04, with the labels that each got.

#110 Add howto on How to expand a chart with hypper
  docs/user/howto/expandcharthypper.md
Labels: documentation, mvp, ready for review

#115 Fix 2 small vet issues
  pkg/action/doc.go
  pkg/eyecandy/emoji.go
Labels: ready for review

#119 Add docs generation to workflows
  .github/workflows/docs-book.yml
  .gitignore
  book.toml
  docs/SUMMARY.md
  docs/user/howto/README.md
  docs/user/tutorials/installing.md
Labels: documentation, enhancement, mvp, ready for review

#109 Add lint command
  cmd/hypper/lint.go
  cmd/hypper/lint_test.go
  cmd/hypper/root.go
  cmd/hypper/testdata/output/lint-chart-with-bad-subcharts-with-subcharts-windows.txt
  cmd/hypper/testdata/output/lint-chart-with-bad-subcharts-with-subcharts.txt
  cmd/hypper/testdata/output/lint-chart-with-bad-subcharts.txt
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/charts/bad-subchart/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/charts/bad-subchart/values.yaml
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/charts/good-subchart/Chart.yaml
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/charts/good-subchart/values.yaml
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/requirements.yaml
  cmd/hypper/testdata/testcharts/chart-with-bad-subcharts/values.yaml
  docs/user/howto/lintchart.md
  pkg/action/lint.go
  pkg/action/lint_test.go
  pkg/action/testdata/charts/chart-with-no-templates-dir/Chart.yaml
  pkg/action/testdata/charts/chart-with-schema-negative/Chart.yaml
  pkg/action/testdata/charts/chart-with-schema-negative/templates/empty.yaml
  pkg/action/testdata/charts/chart-with-schema-negative/values.schema.json
  pkg/action/testdata/charts/chart-with-schema-negative/values.yaml
  pkg/action/testdata/charts/chart-with-schema/Chart.yaml
  pkg/action/testdata/charts/chart-with-schema/extra-values.yaml
  pkg/action/testdata/charts/chart-with-schema/templates/empty.yaml
  pkg/action/testdata/charts/chart-with-schema/values.schema.json
  pkg/action/testdata/charts/chart-with-schema/values.yaml
  pkg/action/testdata/charts/compressedchart-0.1.0.tar.gz
  pkg/action/testdata/charts/compressedchart-0.1.0.tgz
  pkg/action/testdata/charts/compressedchart-with-hyphens-0.1.0.tgz
  pkg/action/testdata/charts/corrupted-compressed-chart.tgz
  pkg/action/testdata/charts/decompressedchart/Chart.yaml
  pkg/action/testdata/charts/decompressedchart/values.yaml
  pkg/action/testdata/charts/multiplecharts-lint-chart-1/Chart.yaml
  pkg/action/testdata/charts/multiplecharts-lint-chart-1/templates/configmap.yaml
  pkg/action/testdata/charts/multiplecharts-lint-chart-1/values.yaml
  pkg/action/testdata/charts/multiplecharts-lint-chart-2/Chart.yaml
  pkg/action/testdata/charts/multiplecharts-lint-chart-2/templates/configmap.yaml
  pkg/action/testdata/charts/multiplecharts-lint-chart-2/values.yaml
  pkg/action/testdata/charts/pre-release-chart-0.1.0-alpha.tgz
  pkg/lint/lint.go
  pkg/lint/lint_test.go
  pkg/lint/rules/annotations.go
  pkg/lint/rules/annotations_test.go
  pkg/lint/rules/testdata/badchart/.helmignore
  pkg/lint/rules/testdata/badchart/Chart.yaml
  pkg/lint/rules/testdata/badchart/templates/.gitkeep
  pkg/lint/rules/testdata/badchart/values.yaml
  pkg/lint/rules/testdata/badchartbrokenhypperdeps/.helmignore
  pkg/lint/rules/testdata/badchartbrokenhypperdeps/Chart.yaml
  pkg/lint/rules/testdata/badchartbrokenhypperdeps/templates/.gitkeep
  pkg/lint/rules/testdata/badchartbrokenhypperdeps/values.yaml
  pkg/lint/rules/testdata/goodchart/.helmignore
  pkg/lint/rules/testdata/goodchart/Chart.yaml
  pkg/lint/rules/testdata/goodchart/templates/.gitkeep
  pkg/lint/rules/testdata/goodchart/values.yaml
Labels: enhancement, ready for review

#113 Add search command
  cmd/hypper/root.go
  cmd/hypper/search.go
  cmd/hypper/search_test.go
  cmd/hypper/testdata/hypperhome/hypper/repositories.yaml
  cmd/hypper/testdata/hypperhome/hypper/repository/test-name-charts.txt
  cmd/hypper/testdata/hypperhome/hypper/repository/test-name-index.yaml
  cmd/hypper/testdata/hypperhome/hypper/repository/testing-index.yaml
  cmd/hypper/testdata/output/search-constraint-single.txt
  cmd/hypper/testdata/output/search-constraint.txt
  cmd/hypper/testdata/output/search-multiple-devel-release.txt
  cmd/hypper/testdata/output/search-multiple-stable-release.txt
  cmd/hypper/testdata/output/search-multiple-versions-constraints.txt
  cmd/hypper/testdata/output/search-multiple-versions.txt
  cmd/hypper/testdata/output/search-not-found.txt
  cmd/hypper/testdata/output/search-output-json.txt
  cmd/hypper/testdata/output/search-output-yaml.txt
  cmd/hypper/testdata/output/search-regex.txt
  cmd/hypper/testdata/output/search-versions-constraint.txt
  cmd/hypper/upgrade_test.go
  docs/user/howto/search.md
  go.mod
  pkg/search/index.go
  pkg/search/index_test.go
  pkg/search/search.go
Labels: ready for review

#118 Fix helm settings for flags
  cmd/hypper/root.go
  pkg/cli/environment.go
Labels: bug, ready for review

#131 docs: Add how-to on shared-deps
  docs/SUMMARY.md
  docs/user/howto/expandcharthypper.md
  docs/user/howto/lintchart.md
  docs/user/howto/search.md
  docs/user/howto/shared-deps.md
  docs/user/tutorials/installing.md
  docs/user/tutorials/quickstart.md
Labels: ready for review

#133 Add link to the slack channel
  README.md
Labels: ready for review

#111 Add pull command
  cmd/hypper/hypper_test.go
  cmd/hypper/pull.go
  cmd/hypper/pull_test.go
  cmd/hypper/root.go
  cmd/hypper/testdata/helm-test-key.pub
  cmd/hypper/testdata/testcharts/compressedchart-0.1.0.tar.gz
  cmd/hypper/testdata/testcharts/compressedchart-0.1.0.tgz
  cmd/hypper/testdata/testcharts/compressedchart-0.2.0.tgz
  cmd/hypper/testdata/testcharts/compressedchart-0.3.0.tgz
  cmd/hypper/testdata/testcharts/compressedchart-with-hyphens-0.1.0.tgz
  cmd/hypper/testdata/testcharts/oci-dependent-chart-0.1.0.tgz
  cmd/hypper/testdata/testcharts/pre-release-chart-0.1.0-alpha.tgz
  cmd/hypper/testdata/testcharts/reqtest-0.1.0.tgz
  cmd/hypper/testdata/testcharts/signtest-0.1.0.tgz
  cmd/hypper/testdata/testcharts/signtest-0.1.0.tgz.prov
  docs/SUMMARY.md
  docs/user/howto/pull.md
  pkg/action/pull.go
Labels: ready for review

#136 Set proper dir for publishing docs
  .github/workflows/docs-book.yml
Labels: bug, documentation, mvp, ready for review

#146 Emoji style guide
  CONTRIBUTING.md
  cmd/hypper/install.go
  cmd/hypper/testdata/output/install-create-namespace.txt
  cmd/hypper/testdata/output/install-fallback-annot.txt
  cmd/hypper/testdata/output/install-hypper-annot.txt
  cmd/hypper/testdata/output/install-name-ns-args.txt
  cmd/hypper/testdata/output/install-no-name-or-annot.txt
  cmd/hypper/testdata/output/install-with-shared-deps.txt
  cmd/hypper/testdata/output/uninstall-keep-history.txt
  cmd/hypper/testdata/output/uninstall-multiple.txt
  cmd/hypper/testdata/output/uninstall-no-hooks.txt
  cmd/hypper/testdata/output/uninstall-timeout.txt
  cmd/hypper/testdata/output/uninstall.txt
  cmd/hypper/testdata/output/upgrade-with-install-release-name.txt
  cmd/hypper/testdata/output/upgrade-with-install-timeout.txt
  cmd/hypper/testdata/output/upgrade-with-install.txt
  cmd/hypper/testdata/output/upgrade-with-release-name.txt
  cmd/hypper/testdata/output/upgrade-with-reset-values.txt
  cmd/hypper/testdata/output/upgrade-with-reset-values2.txt
  cmd/hypper/testdata/output/upgrade-with-timeout.txt
  cmd/hypper/testdata/output/upgrade-with-wait-for-jobs.txt
  cmd/hypper/testdata/output/upgrade-with-wait.txt
  cmd/hypper/testdata/output/upgrade.txt
  cmd/hypper/uninstall.go
  cmd/hypper/upgrade.go
  pkg/action/install.go
  pkg/action/testdata/output/install-correctly-shared-deps.txt
  pkg/action/testdata/output/install-malformed-shared-deps.txt
  pkg/action/testdata/output/install-shared-dep-installed.txt
Labels: ready for review

#114 Add filtering by annotations on search
  cmd/hypper/search.go
  cmd/hypper/search_test.go
  cmd/hypper/testdata/hypperhome/hypper/repository/testing-index.yaml
  cmd/hypper/testdata/output/search-hypper-annotation-regexp.txt
  cmd/hypper/testdata/output/search-hypper-annotation-version-regexp.txt
  cmd/hypper/testdata/output/search-hypper-annotation-version.txt
  cmd/hypper/testdata/output/search-hypper-annotation.txt
  cmd/hypper/testdata/output/search-hypper-latest.txt
  docs/user/howto/searchannotations.md
  pkg/search/doc.go
  pkg/search/index.go
  pkg/search/search.go
Labels: enhancement, ready for review

#153 Fix get_hypper after shellcheck update
  scripts/get-hypper
Labels: ready for review
